@startuml
participant Module1
participant CanBus
participant Module2

activate Module1

Module1 -> CanBus : reserve(1)

note right of Module1 : waiting for collision
activate Module1 #LightBlue

activate Module2
Module2 -> CanBus : reserve(2)
activate Module2 #LightBlue
note right of Module2 : waiting for collision
CanBus -> Module1 : reserve(2)


Module1 -> Module1 : register(1)
deactivate Module1

Module2 -> Module2 : register(2)
deactivate Module2
@enduml
